### ISSUE TITLE
cannot run the script

### ISSUE THREAD

**Issue by harishksoft** [DraganMatesic/pc_tracker#2]
@DraganMatesic 
(venv) D:\python\pc-tracker>
[main 2023-10-05T11:30:41.134Z] update#setState idle
[main 2023-10-05T11:31:11.138Z] update#setState checking for updates
[main 2023-10-05T11:31:11.368Z] update#setState idle

this error shows and main.py opens in the editor. nothing more ;(

**Comment by DraganMatesic** [comment]
there is no Python file named main.py. If you are referring to manage.py try to run it with `python manage.py runclient`
